name: Components and E2E Tests

on:
  workflow_call:
    inputs:
      test-url:
        required: true
        type: string
    outputs:
      result:
        description: "Test results"
        value: ${{ jobs.cypress-run.outputs.result }}
    secrets:
      CYPRESS_RECORD_KEY:
        required: true

jobs:
  cypress-run-components:
    name: Components Tests
    runs-on: ubuntu-22.04
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      # - name: Install dependencies
      #   run: npm ci
      # - name: Cypress run
      #   uses: cypress-io/github-action@v5
      #   with:
      #     start: npm start
      #     component: true
      - name: Skip for now
        run: echo "Skip for now"

  cypress-run-e2e:
    name: E2E Tests
    runs-on: ubuntu-22.04
    outputs:
      result: ${{ steps.result.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          config: baseUrl=${{ inputs.test-url }}
          # wait-on: ${{ inputs.test-url }}
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{github.event.pull_request.title}}
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots/chrome
          if-no-files-found: ignore
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos/chrome
          if-no-files-found: ignore
      - name: Set test result
        id: result
        run: echo "result=${{ job.status }}" >> $GITHUB_OUTPUT
